# GitHub Actions workflow to build the Python package
# Triggered on pushes to tags matching v*.*.*

name: Build Python Package

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags like v1.0.0, v0.1.2, etc.

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        poetry-version: ["latest", "main", "1.8.4"]
        os: [ubuntu-22.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Run image
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install dependencies (optional but good practice)
        run: poetry install --no-interaction --no-root

      - name: Build package
        run: poetry build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-package-${{ github.ref_name }} # Include tag name in artifact name
          path: dist/
